### ISSUE TITLE
Contribution to repository

### ISSUE THREAD

**Issue by mertyavuz41** [niuwengang/multisensor_fusion_localization_study#1]
Hi there,

I would like to contribute to the repository but I slog on use translate japanese to english, it would better to use english for anyone wants to contribute this repository. Could you replace japanese comments with english ones?

Thanks

**Comment by niuwengang** [comment]
Thanks for your contribution,but actually the language of code comments is Chinese not Japanese .
Considering the project is still in development, using my native language is more effective for me. Maybe You can try to learn some Chinese first.
When the entire project is completed,I will try to use English code comments.

**Comment by mertyavuz41** [comment]
It will probably take less time for you to finish the whole project than for me to learn Chinese :)

**Comment by niuwengang** [comment]
My English sucks hahaha ~！Maybe I can give a try. 
You are also welcome to learn some Chinese. Chinese characters have the history of several thousand years.
